# Generated by Django 5.2.17 on 2026-09-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cardpaymentdetails',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_source', 'BANK_ACCOUNT'), ('source_account__isnull', False)), models.Q(('payment_source', 'CASH'), ('source_account__isnull', True)), _connector='OR'), name='payment_source_matches_account'),
        ),
        migrations.AddConstraint(
            model_name='creditcarddetails',
            constraint=models.CheckConstraint(condition=models.Q(('opening_available_credit__lte', models.F('credit_limit'))), name='opening_credit_within_limit'),
        ),
    ]
