# Generated by Django 5.2.17 on 2026-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cardpaymentdetails_payment_source_matches_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('RECEIVED', 'Received'), ('INCOME', 'Income'), ('BONUS', 'Bonus'), ('EXTRA', 'Extra'), ('CARD_PAYMENT', 'Card payment')], max_length=16),
        ),
    ]
