"""URL configuration for config project."""
from django.contrib import admin
from django.urls import path

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/signup/', views.signup, name='api-signup'),
    path('api/auth/login/', views.login_view, name='api-login'),
    path('api/auth/logout/', views.logout_view, name='api-logout'),
    path('logout/', views.logout_page, name='logout-page'),
    path('api/auth/me/', views.current_user, name='api-current-user'),
    path('login/', views.login_page, name='login-page'),
    path('signup/', views.signup_page, name='signup-page'),
    path('api/dashboard/', views.dashboard_api, name='api-dashboard'),
    path('api/people/', views.people, name='api-people'),
    path('api/people/<uuid:person_id>/', views.person_detail, name='api-person-detail'),
    path('api/people/<uuid:person_id>/transactions/', views.person_transactions, name='api-person-transactions'),
    path('api/people/<uuid:person_id>/position/', views.person_position_api, name='api-person-position'),
    path('api/accounts/', views.accounts, name='api-accounts'),
    path('api/accounts/<uuid:account_id>/', views.account_detail, name='api-account-detail'),
    path('api/accounts/<uuid:account_id>/transactions/', views.account_transactions, name='api-account-transactions'),
    path('api/transactions/', views.transactions, name='api-transactions'),
    path('api/card-payments/', views.card_payments_api, name='api-card-payments'),
    path('api/money-transfers/', views.money_transfers_api, name='api-money-transfers'),
    path('api/transactions/<uuid:transaction_id>/', views.transaction_detail, name='api-transaction-detail'),
    path('', views.dashboard_page, name='dashboard'),
    path('people/', views.people_page, name='people-page'),
    path('people/new/', views.person_form_page, name='person-new'),
    path('people/<uuid:person_id>/edit/', views.person_edit_page, name='person-edit'),
    path('people/<uuid:person_id>/archive-toggle/', views.person_archive_toggle_page, name='person-archive-toggle'),
    path('accounts/', views.accounts_page, name='accounts-page'),
    path('accounts/new/', views.account_form_page, name='account-new'),
    path('accounts/<uuid:account_id>/edit/', views.account_edit_page, name='account-edit'),
    path('accounts/<uuid:account_id>/archive-toggle/', views.account_archive_toggle_page, name='account-archive-toggle'),
    path('transactions/', views.transactions_page, name='transactions-page'),
    path('transactions/import/', views.transaction_import_page, name='transaction-import'),
    path('transactions/export/', views.transaction_export_page, name='transaction-export'),
    path('transactions/import/template/', views.transaction_import_template, name='transaction-import-template'),
    path('transactions/new/', views.transaction_form_page, name='transaction-new'),
    path('transactions/<uuid:transaction_id>/edit/', views.transaction_edit_page, name='transaction-edit'),
    path('transactions/<uuid:transaction_id>/void/', views.transaction_void_page, name='transaction-void'),
    path('transactions/<uuid:transaction_id>/restore/', views.transaction_restore_page, name='transaction-restore'),
    path('card-payments/new/', views.card_payment_form_page, name='card-payment-new'),
    path('money-transfers/new/', views.money_transfer_form_page, name='money-transfer-new'),
    path('money-transfers/<uuid:transaction_id>/edit/', views.money_transfer_form_page, name='money-transfer-edit'),
    path('settings/', views.settings_page, name='settings-page'),
    path('profile/', views.profile_page, name='profile-page'),
    path('settings/people/<uuid:person_id>/restore/', views.restore_person_page, name='person-restore'),
    path('settings/accounts/<uuid:account_id>/restore/', views.restore_account_page, name='account-restore'),
]
